import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Any code that you define there will be displayed on every page of the app, used for headers, footers...
// You can additionally nest layout files in directories and those layouts will only affect the pages and their children that are nested in those directories
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Comment out later, used for navigation Notes app */}
      {/* <body>
        <main>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/notes">Notes</Link>
          </nav>
          {children}
        </main>
      </body> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
